name: Build and push to ghcr.io

on:
  workflow_call:
    inputs:
      scrypto_version:
        required: true
        type: string

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Build and push
          run: |
            docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.PACKAGE_MANAGER_PW }}
            docker build -f Dockerfile.${{ inputs.scrypto_version }}  -t ghcr.io/${{ github.repository }}:${{ inputs.scrypto_version }} .
            docker push ghcr.io/${{ github.repository }}:${{ inputs.scrypto_version }}

              