name: Build and push to ghcr.io for Scrypto 1.0.0

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build_and_push_1.0.0.yml

jobs:
  check-and-build:
    permissions:
      contents: write
      pull-requests: write
    uses: atoumbre/scrypto-builder/.github/workflows/build_and_push.yml@master
    with:
      scrypto_version: 1.0.0

              